"""
AI Productivity Assistant — Streamlit Web App
CAPACITI AI Skill Accelerator Programme

Features:
  1. Smart Email Generator
  2. Meeting Notes Summarizer
  3. AI Task Planner / Scheduler
  4. AI Research Assistant
  5. Interactive AI Chatbot

Deployment: Streamlit Community Cloud
"""

import os
import re
import streamlit as st
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------
MODEL_ID = "gemini-3.5-flash"
TEMPERATURE = 0.7
MAX_OUTPUT_TOKENS = 8192

SYSTEM_INSTRUCTION = (
    "You are an AI Workplace Productivity Assistant. Help professionals "
    "with emails, meeting summaries, task planning, and research. Be clear, "
    "concise, and professional. Use Markdown. Ask clarifying questions if "
    "needed. Do not provide legal, medical, or financial advice. Always "
    "remind the user to verify AI-generated content."
)

DISCLAIMER = """
⚠️ **Responsible AI Notice:** This output was generated by Gemini 3.5 Flash. 
It may contain errors, omissions, or biases. Verify all facts before use. 
Do not share confidential information. You remain responsible for the final output.
"""

# ------------------------------------------------------------------
# Prompt Templates
# ------------------------------------------------------------------
EMAIL_PROMPT = """You are a professional business communication assistant.
TASK: Draft a {tone} email to a {audience}.
CONTEXT:
- Sender: {sender}
- Recipient: {recipient}
- Subject: {subject}
- Key points: {key_points}
- Length: {length}
CONSTRAINTS:
- Use a {tone} tone throughout.
- Do not invent facts that were not provided.
- Return only the email text (subject line + body).
"""

NOTES_PROMPT = """You are an expert meeting-minutes assistant.
TASK: Summarise the following meeting notes into a structured report.
NOTES:
---
{notes}
---
OUTPUT SECTIONS:
1. Summary (3-5 sentences)
2. Key Points (bullets)
3. Decisions Made (bullets)
4. Action Items (table: Action | Owner | Deadline)
5. Next Steps
CONSTRAINTS:
- Only use information present in the notes.
- If owner/deadline missing, write "Not specified".
- Return Markdown.
"""

PLAN_PROMPT = """You are a productivity and time-management coach.
TASK: Create a {plan_type} plan for the following tasks.
USER: {user_name}
WORKING HOURS: {working_hours}
FIXED COMMITMENTS: {fixed}
TASKS:
{tasks}
Use the Eisenhower Matrix (Urgent + Important).
OUTPUT:
1. Priority Matrix (table with quadrant classification)
2. Time-Blocked Schedule
3. Time Optimisation Tips (3-5 suggestions)
4. Potential Risks
CONSTRAINTS:
- Respect working hours.
- Include breaks every 90 minutes.
- Do not over-schedule.
"""

RESEARCH_PROMPT = """You are a senior research analyst.
TASK: Analyse the following {content_type} and produce a research brief.
CONTENT:
---
{content}
---
OUTPUT SECTIONS:
1. Executive Summary (3-4 sentences)
2. Key Insights (5-7 bullets)
3. Data & Evidence
4. Implications
5. Recommendations (3 actions)
6. Limitations
CONSTRAINTS:
- Remain objective and evidence-based.
- Distinguish source facts from interpretation.
- If insufficient data, write "Insufficient data".
- Return Markdown.
"""

# ------------------------------------------------------------------
# Gemini Client
# ------------------------------------------------------------------
@st.cache_resource
def get_client():
    # Try Streamlit secrets first, then environment variables
    api_key = None
    try:
        api_key = st.secrets["GEMINI_API_KEY"]
    except Exception:
        api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")

    if not api_key:
        st.error("🔑 **API Key Missing!** Please add `GEMINI_API_KEY` to your Streamlit Secrets or `.env` file.")
        st.stop()
    
    return genai.Client(api_key=api_key)

def ask_gemini(client, prompt, temperature=TEMPERATURE):
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            temperature=temperature,
            max_output_tokens=MAX_OUTPUT_TOKENS,
        ),
    )
    return response.text

# ------------------------------------------------------------------
# Responsible AI Helpers
# ------------------------------------------------------------------
SENSITIVE_PATTERNS = [
    (r"\b\d{3}-\d{2}-\d{4}\b", "US Social Security Number"),
    (r"\b\d{16}\b", "Credit card number"),
    (r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b", "Email address"),
    (r"\b(?:\+27|0)\d{9}\b", "South African phone number"),
    (r"\b\d{13}\b", "South African ID number"),
]

def check_sensitive_data(text):
    found = [label for pattern, label in SENSITIVE_PATTERNS if re.search(pattern, text)]
    if found:
        st.warning(f"⚠️ **Sensitive data detected:** {', '.join(found)}. Please remove before submitting.")
        return False
    return True

def show_disclaimer():
    st.info(DISCLAIMER)

# ------------------------------------------------------------------
# UI Setup
# ------------------------------------------------------------------
st.set_page_config(page_title="AI Productivity Assistant", page_icon="🤖", layout="wide")
st.title("🤖 AI Productivity Assistant")
st.caption("Powered by Gemini 3.5 Flash | CAPACITI AI Skill Accelerator")

# Sidebar Navigation
st.sidebar.title("Navigation")
feature = st.sidebar.radio(
    "Select a Feature:",
    [
        "📧 Smart Email Generator",
        "📝 Meeting Notes Summarizer",
        "📅 AI Task Planner",
        "🔍 AI Research Assistant",
        "💬 Interactive Chatbot"
    ]
)

st.sidebar.markdown("---")
st.sidebar.info("Built for the CAPACITI AI Skill Accelerator Programme.")

client = get_client()

# ==================================================================
# FEATURE 1: Smart Email Generator
# ==================================================================
if feature == "📧 Smart Email Generator":
    st.header("📧 Smart Email Generator")
    st.write("Generate context-aware professional emails.")

    col1, col2 = st.columns(2)
    with col1:
        sender = st.text_input("Your Name", "Thandi Mokoena")
        recipient = st.text_input("Recipient Name", "Mr. Naidoo")
        subject = st.text_input("Subject / Purpose", "Request for project deadline extension")
    with col2:
        audience = st.selectbox("Audience", ["Client", "Manager", "Team", "Colleague"])
        tone = st.selectbox("Tone", ["Formal", "Informal", "Persuasive"])
        length = st.selectbox("Length", ["Short", "Medium", "Detailed"])

    key_points = st.text_area("Key Points (comma-separated)", "Load-shedding affected progress, new deadline proposed, offer mitigation plan")

    if st.button("Generate Email", type="primary"):
        if not subject or not key_points:
            st.error("Subject and Key Points are required.")
        elif not check_sensitive_data(key_points):
            pass
        else:
            with st.spinner("Drafting email..."):
                prompt = EMAIL_PROMPT.format(
                    sender=sender, recipient=recipient, subject=subject,
                    key_points=key_points, audience=audience, tone=tone, length=length
                )
                try:
                    output = ask_gemini(client, prompt)
                    st.markdown("### 📩 Generated Email")
                    st.markdown(output)
                    show_disclaimer()
                except Exception as e:
                    st.error(f"Error: {e}")

# ==================================================================
# FEATURE 2: Meeting Notes Summarizer
# ==================================================================
elif feature == "📝 Meeting Notes Summarizer":
    st.header("📝 Meeting Notes Summarizer")
    st.write("Convert lengthy notes into concise summaries with action items.")

    notes = st.text_area("Paste your meeting notes here:", height=300, placeholder="Paste raw notes...")

    if st.button("Summarize Notes", type="primary"):
        if not notes:
            st.error("Please provide meeting notes.")
        elif not check_sensitive_data(notes):
            pass
        else:
            with st.spinner("Summarising..."):
                prompt = NOTES_PROMPT.format(notes=notes)
                try:
                    output = ask_gemini(client, prompt)
                    st.markdown("### 📋 Meeting Summary")
                    st.markdown(output)
                    show_disclaimer()
                except Exception as e:
                    st.error(f"Error: {e}")

# ==================================================================
# FEATURE 3: AI Task Planner / Scheduler
# ==================================================================
elif feature == "📅 AI Task Planner":
    st.header("📅 AI Task Planner / Scheduler")
    st.write("Prioritise tasks with the Eisenhower Matrix and build a time-blocked plan.")

    col1, col2 = st.columns(2)
    with col1:
        user_name = st.text_input("Your Name", "User")
        plan_type = st.selectbox("Plan Type", ["Daily", "Weekly"])
    with col2:
        working_hours = st.text_input("Working Hours", "09:00-17:00")
        fixed = st.text_input("Fixed Commitments", "None")

    tasks = st.text_area(
        "Tasks (one per line): Format: Task | urgency (high/med/low) | importance (high/med/low)",
        height=200,
        placeholder="Finish report | high | high\nReview emails | low | medium\nPrepare presentation | high | high"
    )

    if st.button("Build Plan", type="primary"):
        if not tasks:
            st.error("Please provide at least one task.")
        elif not check_sensitive_data(tasks):
            pass
        else:
            with st.spinner("Building your plan..."):
                prompt = PLAN_PROMPT.format(
                    plan_type=plan_type, user_name=user_name,
                    working_hours=working_hours, fixed=fixed, tasks=tasks
                )
                try:
                    output = ask_gemini(client, prompt)
                    st.markdown("### 📅 Your Optimised Plan")
                    st.markdown(output)
                    show_disclaimer()
                except Exception as e:
                    st.error(f"Error: {e}")

# ==================================================================
# FEATURE 4: AI Research Assistant
# ==================================================================
elif feature == "🔍 AI Research Assistant":
    st.header("🔍 AI Research Assistant")
    st.write("Summarise articles, reports, or topics into a structured research brief.")

    content_type = st.selectbox("Content Type", ["Article", "Report", "Topic", "Other"])
    content = st.text_area("Paste the content here:", height=300, placeholder="Paste article or report text...")

    if st.button("Analyse Content", type="primary"):
        if not content:
            st.error("Please provide content to analyse.")
        elif not check_sensitive_data(content):
            pass
        else:
            with st.spinner("Analysing..."):
                prompt = RESEARCH_PROMPT.format(content_type=content_type, content=content)
                try:
                    output = ask_gemini(client, prompt)
                    st.markdown("### 📊 Research Brief")
                    st.markdown(output)
                    show_disclaimer()
                except Exception as e:
                    st.error(f"Error: {e}")

# ==================================================================
# FEATURE 5: Interactive AI Chatbot
# ==================================================================
elif feature == "💬 Interactive Chatbot":
    st.header("💬 Interactive AI Chatbot")
    st.write("Your personal workplace productivity assistant.")

    # Initialize chat history
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # Display chat messages from history
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Accept user input
    if prompt := st.chat_input("Ask me anything about productivity, emails, or planning..."):
        # Add user message to chat history
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Generate response
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                try:
                    # Convert history to Gemini format
                    history = []
                    for msg in st.session_state.messages:
                        role = "user" if msg["role"] == "user" else "model"
                        history.append(types.Content(role=role, parts=[types.Part.from_text(text=msg["content"])]))
                    
                    response = client.models.generate_content(
                        model=MODEL_ID,
                        contents=history,
                        config=types.GenerateContentConfig(
                            system_instruction=SYSTEM_INSTRUCTION,
                            temperature=TEMPERATURE,
                            max_output_tokens=MAX_OUTPUT_TOKENS,
                        ),
                    )
                    st.markdown(response.text)
                    st.session_state.messages.append({"role": "assistant", "content": response.text})
                    show_disclaimer()
                except Exception as e:
                    st.error(f"Error: {e}")
