"""
AI Productivity Assistant
CAPACITI AI Skill Accelerator Programme

A CLI app using Google Gemini 3.5 Flash to automate:
  1. Smart Email Generator
  2. Meeting Notes Summarizer
  3. AI Task Planner / Scheduler
  4. AI Research Assistant
  5. Interactive AI Chatbot

Usage:
    python app.py                  # interactive menu
    python app.py email            # Smart Email Generator
    python app.py notes            # Meeting Notes Summarizer
    python app.py plan             # AI Task Planner
    python app.py research         # AI Research Assistant
    python app.py chat             # Chatbot
    python app.py chat --stream    # Chatbot with streaming
"""

import os
import re
import sys
import argparse
import logging
from datetime import datetime

from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

# ================================================================== #
# CONFIGURATION
# ================================================================== #
MODEL_ID = "gemini-3.5-flash"
TEMPERATURE = 0.7
MAX_OUTPUT_TOKENS = 8192
MAX_INPUT_CHARS = 30_000
MIN_INPUT_CHARS = 10

SYSTEM_INSTRUCTION = (
    "You are an AI Workplace Productivity Assistant. Help professionals "
    "with emails, meeting summaries, task planning, and research. Be clear, "
    "concise, and professional. Use Markdown. Ask clarifying questions if "
    "needed. Do not provide legal, medical, or financial advice. Always "
    "remind the user to verify AI-generated content."
)

DISCLAIMER = """
────────────────────────────────────────────────────────────
⚠️  RESPONSIBLE AI NOTICE
This output was generated by Gemini 3.5 Flash. It may contain
errors, omissions, or biases. Verify all facts before use. Do
not share confidential information. You remain responsible
for the final output.  Learn more: https://ai.google.dev/responsible
────────────────────────────────────────────────────────────
"""

# ================================================================== #
# PROMPT TEMPLATES (R-T-C-F framework)
# ================================================================== #
EMAIL_PROMPT = """You are a professional business communication assistant.

TASK: Draft a {tone} email to a {audience}.

CONTEXT:
- Sender: {sender}
- Recipient: {recipient}
- Subject: {subject}
- Key points: {key_points}
- Length: {length}

CONSTRAINTS:
- Use a {tone} tone throughout.
- Do not invent facts that were not provided.
- Return only the email text (subject line + body).
"""

NOTES_PROMPT = """You are an expert meeting-minutes assistant.

TASK: Summarise the following meeting notes into a structured report.

NOTES:
---
{notes}
---

OUTPUT SECTIONS:
1. Summary (3-5 sentences)
2. Key Points (bullets)
3. Decisions Made (bullets)
4. Action Items (table: Action | Owner | Deadline)
5. Next Steps

CONSTRAINTS:
- Only use information present in the notes.
- If owner/deadline missing, write "Not specified".
- Return Markdown.
"""

PLAN_PROMPT = """You are a productivity and time-management coach.

TASK: Create a {plan_type} plan for the following tasks.

USER: {user_name}
WORKING HOURS: {working_hours}
FIXED COMMITMENTS: {fixed}
TASKS:
{tasks}

Use the Eisenhower Matrix (Urgent + Important).

OUTPUT:
1. Priority Matrix (table with quadrant classification)
2. Time-Blocked Schedule
3. Time Optimisation Tips (3-5 suggestions)
4. Potential Risks

CONSTRAINTS:
- Respect working hours.
- Include breaks every 90 minutes.
- Do not over-schedule.
"""

RESEARCH_PROMPT = """You are a senior research analyst.

TASK: Analyse the following {content_type} and produce a research brief.

CONTENT:
---
{content}
---

OUTPUT SECTIONS:
1. Executive Summary (3-4 sentences)
2. Key Insights (5-7 bullets)
3. Data & Evidence
4. Implications
5. Recommendations (3 actions)
6. Limitations

CONSTRAINTS:
- Remain objective and evidence-based.
- Distinguish source facts from interpretation.
- If insufficient data, write "Insufficient data".
- Return Markdown.
"""

# ================================================================== #
# RESPONSIBLE AI
# ================================================================== #
SENSITIVE_PATTERNS = [
    (r"\b\d{3}-\d{2}-\d{4}\b", "US Social Security Number"),
    (r"\b\d{16}\b", "Credit card number"),
    (r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b", "Email address"),
    (r"\b(?:\+27|0)\d{9}\b", "South African phone number"),
    (r"\b\d{13}\b", "South African ID number"),
    (r"password\s*[:=]\s*\S+", "Password"),
    (r"api[_-]?key\s*[:=]\s*\S+", "API key"),
]

HALLUCINATION_MARKERS = [
    r"\[\d+\]",
    r"according to a study",
    r"research shows that",
    r"statistics indicate",
    r"a recent report",
]

logging.basicConfig(
    filename="ai_assistant_audit.log",
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)


def detect_sensitive(text: str) -> list[str]:
    return [label for pattern, label in SENSITIVE_PATTERNS if re.search(pattern, text)]


def validate_input(text: str, feature: str = "general") -> tuple[bool, str]:
    if not text or not text.strip():
        return False, "Input is empty."
    s = text.strip()
    if len(s) < MIN_INPUT_CHARS:
        return False, f"Input too short ({len(s)} chars). Minimum {MIN_INPUT_CHARS}."
    if len(s) > MAX_INPUT_CHARS:
        return False, f"Input too long ({len(s):,} chars). Max {MAX_INPUT_CHARS:,}."

    found = detect_sensitive(s)
    if found:
        msg = "⚠️  Sensitive data detected:\n" + "\n".join(f"   • {x}" for x in found)
        msg += "\n\nRemove before continuing. Do not share confidential data with the AI."
        return False, msg
    return True, s


def flag_hallucinations(text: str) -> list[str]:
    return [
        f"Phrase '{m}' may indicate an unverified claim. Verify independently."
        for m in HALLUCINATION_MARKERS
        if re.search(m, text, re.IGNORECASE)
    ]


def log_audit(feature: str, length: int, success: bool, note: str = "") -> None:
    entry = f"feature={feature} | input_chars={length} | success={success}"
    if note:
        entry += f" | note={note[:80]}"
    logging.info(entry) if success else logging.warning(entry)


# ================================================================== #
# GEMINI CLIENT
# ================================================================== #
def get_client() -> genai.Client:
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if not api_key:
        print(
            "\n[ERROR] No API key found.\n"
            "Set GEMINI_API_KEY in .env or environment.\n"
            "Get a key: https://aistudio.google.com/apikey\n",
            file=sys.stderr,
        )
        sys.exit(1)
    return genai.Client(api_key=api_key)


def ask(client: genai.Client, prompt: str, temperature: float = TEMPERATURE) -> str:
    resp = client.models.generate_content(
        model=MODEL_ID,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            temperature=temperature,
            max_output_tokens=MAX_OUTPUT_TOKENS,
        ),
    )
    return resp.text


def print_result(text: str) -> None:
    print("\n" + "─" * 60)
    print(text)
    print("─" * 60)
    print(DISCLAIMER)
    warnings = flag_hallucinations(text)
    if warnings:
        print("\n⚠️  VERIFICATION SUGGESTIONS:")
        for w in warnings:
            print(f"   • {w}")


def read_multiline(instruction: str) -> str:
    print(instruction)
    print("Type 'END' on a new line when finished.\n")
    lines = []
    while True:
        try:
            line = input()
        except EOFError:
            break
        if line.strip().upper() == "END":
            break
        lines.append(line)
    return "\n".join(lines).strip()


# ================================================================== #
# FEATURE 1: Smart Email Generator
# ================================================================== #
def feature_email(client: genai.Client) -> None:
    print("\n" + "=" * 60)
    print("  📧  SMART EMAIL GENERATOR")
    print("=" * 60)

    sender = input("Your name: ").strip() or "Sender"
    recipient = input("Recipient name: ").strip() or "Recipient"
    subject = input("Subject / purpose: ").strip()
    key_points = input("Key points (comma-separated): ").strip()
    audience = input("Audience (client / manager / team): ").strip() or "colleague"
    tone = input("Tone (formal / informal / persuasive): ").strip() or "formal"
    length = input("Length (short / medium / detailed): ").strip() or "medium"

    if not subject or not key_points:
        print("❌ Subject and key points are required.")
        return

    prompt = EMAIL_PROMPT.format(
        sender=sender, recipient=recipient, subject=subject,
        key_points=key_points, audience=audience, tone=tone, length=length,
    )

    valid, result = validate_input(prompt, "email")
    if not valid:
        print(f"\n❌ {result}")
        log_audit("email", len(prompt), False, result)
        return

    print("\n⏳ Generating email...")
    try:
        output = ask(client, prompt)
        print_result(output)
        log_audit("email", len(prompt), True)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        log_audit("email", len(prompt), False, str(e))


# ================================================================== #
# FEATURE 2: Meeting Notes Summarizer
# ================================================================== #
def feature_notes(client: genai.Client) -> None:
    print("\n" + "=" * 60)
    print("  📝  MEETING NOTES SUMMARIZER")
    print("=" * 60)

    notes = read_multiline("Paste your meeting notes below.")
    if not notes:
        print("❌ No notes provided.")
        return

    valid, result = validate_input(notes, "notes")
    if not valid:
        print(f"\n❌ {result}")
        log_audit("notes", len(notes), False, result)
        return

    prompt = NOTES_PROMPT.format(notes=notes)
    print("\n⏳ Summarising...")
    try:
        output = ask(client, prompt)
        print_result(output)
        log_audit("notes", len(notes), True)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        log_audit("notes", len(notes), False, str(e))


# ================================================================== #
# FEATURE 3: AI Task Planner / Scheduler
# ================================================================== #
def feature_plan(client: genai.Client) -> None:
    print("\n" + "=" * 60)
    print("  📅  AI TASK PLANNER / SCHEDULER")
    print("=" * 60)

    user_name = input("Your name: ").strip() or "User"
    plan_type = input("Plan type (daily / weekly): ").strip() or "daily"
    working_hours = input("Working hours (e.g. 09:00-17:00): ").strip() or "09:00-17:00"
    fixed = input("Fixed commitments (or blank): ").strip() or "None"

    tasks = read_multiline(
        "Enter tasks, one per line. Format: Task | urgency (high/med/low) | importance (high/med/low)"
    )
    if not tasks:
        print("❌ No tasks provided.")
        return

    valid, result = validate_input(tasks, "plan")
    if not valid:
        print(f"\n❌ {result}")
        log_audit("plan", len(tasks), False, result)
        return

    prompt = PLAN_PROMPT.format(
        plan_type=plan_type, user_name=user_name,
        working_hours=working_hours, fixed=fixed, tasks=tasks,
    )

    print("\n⏳ Building your plan...")
    try:
        output = ask(client, prompt)
        print_result(output)
        log_audit("plan", len(tasks), True)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        log_audit("plan", len(tasks), False, str(e))


# ================================================================== #
# FEATURE 4: AI Research Assistant
# ================================================================== #
def feature_research(client: genai.Client) -> None:
    print("\n" + "=" * 60)
    print("  🔍  AI RESEARCH ASSISTANT")
    print("=" * 60)

    content_type = input("Content type (article / report / topic): ").strip() or "article"
    content = read_multiline("Paste the content below.")
    if not content:
        print("❌ No content provided.")
        return

    valid, result = validate_input(content, "research")
    if not valid:
        print(f"\n❌ {result}")
        log_audit("research", len(content), False, result)
        return

    prompt = RESEARCH_PROMPT.format(content_type=content_type, content=content)
    print("\n⏳ Analysing...")
    try:
        output = ask(client, prompt)
        print_result(output)
        log_audit("research", len(content), True)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        log_audit("research", len(content), False, str(e))


# ================================================================== #
# FEATURE 5: Interactive AI Chatbot
# ================================================================== #
def feature_chat(client: genai.Client, stream: bool = False) -> None:
    print("\n" + "=" * 60)
    print("  💬  AI WORKPLACE CHATBOT")
    print(f"  Model: {MODEL_ID}  |  Streaming: {stream}")
    print("  Type 'exit' or 'quit' to stop.")
    print("=" * 60 + "\n")

    history: list[types.Content] = []

    while True:
        try:
            user_input = input("You: ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nGoodbye!")
            break

        if not user_input:
            continue
        if user_input.lower() in {"exit", "quit"}:
            print("Goodbye!")
            break

        history.append(
            types.Content(role="user", parts=[types.Part.from_text(text=user_input)])
        )

        try:
            if stream:
                print("Assistant: ", end="", flush=True)
                stream_resp = client.models.generate_content_stream(
                    model=MODEL_ID,
                    contents=history,
                    config=types.GenerateContentConfig(
                        system_instruction=SYSTEM_INSTRUCTION,
                        temperature=TEMPERATURE,
                        max_output_tokens=MAX_OUTPUT_TOKENS,
                    ),
                )
                full = ""
                for chunk in stream_resp:
                    if chunk.text:
                        print(chunk.text, end="", flush=True)
                        full += chunk.text
                print()
                history.append(
                    types.Content(role="model", parts=[types.Part.from_text(text=full)])
                )
            else:
                resp = client.models.generate_content(
                    model=MODEL_ID,
                    contents=history,
                    config=types.GenerateContentConfig(
                        system_instruction=SYSTEM_INSTRUCTION,
                        temperature=TEMPERATURE,
                        max_output_tokens=MAX_OUTPUT_TOKENS,
                    ),
                )
                print(f"Assistant: {resp.text}\n")
                history.append(
                    types.Content(role="model", parts=[types.Part.from_text(text=resp.text)])
                )
        except Exception as e:
            print(f"\n[ERROR] {e}\n", file=sys.stderr)

    print(DISCLAIMER)


# ================================================================== #
# INTERACTIVE MENU
# ================================================================== #
def menu(client: genai.Client) -> None:
    banner = """
╔══════════════════════════════════════════════════════════╗
║       AI PRODUCTIVITY ASSISTANT — Gemini 3.5 Flash       ║
╠══════════════════════════════════════════════════════════╣
║  1.  📧  Smart Email Generator                           ║
║  2.  📝  Meeting Notes Summarizer                        ║
║  3.  📅  AI Task Planner / Scheduler                     ║
║  4.  🔍  AI Research Assistant                           ║
║  5.  💬  Interactive AI Chatbot                          ║
║  0.  🚪  Exit                                            ║
╚══════════════════════════════════════════════════════════╝
"""
    while True:
        print(banner)
        choice = input("Select option (0-5): ").strip()

        if choice == "0":
            print("\nGoodbye! Remember to verify all AI output. 👋")
            break
        elif choice == "1":
            feature_email(client)
        elif choice == "2":
            feature_notes(client)
        elif choice == "3":
            feature_plan(client)
        elif choice == "4":
            feature_research(client)
        elif choice == "5":
            feature_chat(client, stream=False)
        else:
            print("Invalid choice.")
            continue

        input("\nPress Enter to return to the menu...")


# ================================================================== #
# ENTRY POINT
# ================================================================== #
def main() -> None:
    parser = argparse.ArgumentParser(
        description="AI Productivity Assistant — Gemini 3.5 Flash",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python app.py                  # interactive menu\n"
            "  python app.py email            # Smart Email Generator\n"
            "  python app.py notes            # Meeting Notes Summarizer\n"
            "  python app.py plan             # AI Task Planner\n"
            "  python app.py research         # AI Research Assistant\n"
            "  python app.py chat             # Chatbot\n"
            "  python app.py chat --stream    # Chatbot with streaming\n"
        ),
    )
    parser.add_argument(
        "command", nargs="?",
        choices=["email", "notes", "plan", "research", "chat"],
        help="Feature to run directly",
    )
    parser.add_argument(
        "--stream", action="store_true",
        help="Stream chatbot responses token-by-token",
    )
    args = parser.parse_args()

    client = get_client()

    if args.command == "email":
        feature_email(client)
    elif args.command == "notes":
        feature_notes(client)
    elif args.command == "plan":
        feature_plan(client)
    elif args.command == "research":
        feature_research(client)
    elif args.command == "chat":
        feature_chat(client, stream=args.stream)
    else:
        menu(client)


if __name__ == "__main__":
    main()
